name: "Plan Torque Environment"
description: "Plan an Environment in Torque vs a running environment"
author: "Quali"
inputs:
  space:
    description: "The Torque space to start the environment in"
    required: true
  environment_id:
    description: "Provide a id for the Environment"
    required: false
  env_file_path:
    description: "Path to new environment YAML"
    required: false
  torque_token:
    description: "A Torque longterm token"
    required: true
  torque_hostname:
    description: "Alternative Torque server url"
    required: false
    default: portal.qtorque.io

outputs:
  plan_result:
    description: "The plan result from Torque"
    
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.environment_id }}
    - ${{ inputs.env_file_path}}

  env:
    TORQUE_TOKEN: ${{ inputs.torque_token }}
    TORQUE_SPACE: ${{ inputs.space }}
    TORQUE_HOSTNAME: ${{ inputs.torque_hostname }}
    TORQUE_USERAGENT: Torque-Plugin-Github-Plan-Environment-Action/v1
    TORQUE_URL: ${{ inputs.torque_hostname }} 

branding:
  icon: "play-circle"
  color: "blue"
